import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(resolve(here, 'icons.manifest.json'), 'utf8'));
const RAW = 'https://raw.githubusercontent.com/game-icons/icons/master/';

const tree = await (await fetch('https://api.github.com/repos/game-icons/icons/git/trees/master?recursive=1')).json();
const byName = new Map();
for (const { path } of tree.tree) {
  if (!path.endsWith('.svg')) continue;
  const base = path.split('/').pop().replace(/\.svg$/, '');
  const cur = byName.get(base);
  if (!cur || (cur.startsWith('badges/') && !path.startsWith('badges/'))) byName.set(base, path);
}

const out = {};
const missing = [];
const cache = new Map();
const entries = Object.entries(manifest);
let idx = 0;
async function worker() {
  while (idx < entries.length) {
    const [alias, base] = entries[idx++];
    const path = byName.get(base);
    if (!path) { missing.push(`${alias} -> ${base}`); continue; }
    if (!cache.has(base)) {
      cache.set(base, fetch(RAW + path).then(r => r.text()).then(svg => {
        const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]).filter(d => !/^M0 0h512v512H0z/i.test(d));
        return ds.join(' ');
      }));
    }
    out[alias] = await cache.get(base);
  }
}
await Promise.all(Array.from({ length: 12 }, worker));

if (missing.length) console.warn('MISSING:\n' + missing.join('\n'));
const sorted = Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
mkdirSync(resolve(here, '../src/data'), { recursive: true });
writeFileSync(
  resolve(here, '../src/data/icon-paths.ts'),
  `// Generated by scripts/fetch-icons.mjs from game-icons.net (CC BY 3.0). See public/licenses/game-icons-license.txt.\nexport const ICON_PATHS: Record<string, string> = ${JSON.stringify(sorted)};\n`,
);
console.log(`Wrote ${Object.keys(sorted).length} icons (${missing.length} missing)`);
