import type{Item,Region,Skill,StoryEvent}from'./types';
export const REGIONS:Region[]=[
{id:'catacombs',name:'The Drowned Catacombs',subtitle:'Where the dead refuse the tide',description:'Flooded crypts beneath Veyr. The bells ring under water.',art:'r_catacombs.webp',pos:[48,68],danger:1,unlock:0,boss:'The Bell-Widow'},
{id:'ashwood',name:'Ashwood Expanse',subtitle:'A forest that remembers fire',description:'Black trees bleed embers. Lanterns lead travelers in circles.',art:'r_ashwood.webp',pos:[66,51],danger:2,unlock:1,boss:'The Cinder Hart'},
{id:'quarry',name:'Ossuary Quarry',subtitle:'The old world had larger bones',description:'Miners carved a city through the skeletons of forgotten gods.',art:'r_quarry.webp',pos:[29,45],danger:3,unlock:2,boss:'Foreman Grist'},
{id:'pass',name:'The Weeping Pass',subtitle:'Every frozen corpse faces south',description:'A lost army waits beneath the snow for one final command.',art:'r_pass.webp',pos:[51,20],danger:4,unlock:3,boss:'General Vhal'},
{id:'meridian',name:'The Black Meridian',subtitle:'The wound at the end of the world',description:'Here the sky opens and every possible ending screams at once.',art:'city.webp',pos:[49,88],danger:5,unlock:4,boss:'The King Behind Noon'}];
export const ITEMS:Item[]=[
{id:'rustblade',name:'Notched Sabre',icon:'⚔',type:'weapon',desc:'Reliable steel. +2 damage.',price:40,power:2},{id:'pistol',name:'Grave-Iron Pistol',icon:'⌁',type:'weapon',desc:'Built from coffin nails. +4 damage.',price:130,power:4},{id:'coat',name:'Watchman Coat',icon:'♜',type:'armor',desc:'Blood stiffens its seams. +2 armor.',price:80,power:2},{id:'mail',name:'Saintbone Mail',icon:'♙',type:'armor',desc:'Small prayers carved in ivory. +4 armor.',price:210,power:4},{id:'eye',name:'Sealed Glass Eye',icon:'◉',type:'charm',desc:'+2 Will. Sometimes looks away.',price:95,power:2},{id:'teeth',name:'Wolf-Saint Teeth',icon:'⋈',type:'charm',desc:'+2 Vigor. Warm to the touch.',price:95,power:2},{id:'tonic',name:'Red Tonic',icon:'⚗',type:'consumable',desc:'Restore 14 health.',price:25,power:14},{id:'incense',name:'Quiet Incense',icon:'♨',type:'consumable',desc:'Restore 10 sanity.',price:30,power:10}];
export const SKILLS:Skill[]=[
{id:'sever',name:'Sever',icon:'⚔',school:'Steel',desc:'A brutal strike for 160% weapon damage.',cost:1,cooldown:2,kind:'damage'},
{id:'riposte',name:'Riposte',icon:'⟲',school:'Steel',desc:'Deal damage and gain a ward.',cost:1,cooldown:3,kind:'ward'},
{id:'cinder',name:'Cinder Hex',icon:'♨',school:'Occult',desc:'Burn the enemy with forbidden flame.',cost:1,cooldown:3,kind:'damage'},
{id:'mend',name:'Blood Mend',icon:'♥',school:'Sanguine',desc:'Trade 2 sanity to restore health.',cost:1,cooldown:4,kind:'heal'},
{id:'still',name:'Still Mind',icon:'◉',school:'Discipline',desc:'Restore sanity and clear fear.',cost:1,cooldown:4,kind:'sanity'},
{id:'void',name:'Void Lance',icon:'✦',school:'Astral',desc:'High damage that ignores armor.',cost:2,cooldown:4,kind:'damage'}];
export const EVENTS:StoryEvent[]=[
{id:'well',title:'The Well That Knows You',icon:'◉',text:'At a junction drowned ankle-deep, a stone well whispers your childhood name. A silver coin spins on its black surface without sinking.',choices:[{label:'Take the coin',text:'Reach into the water.',effect:'gold'},{label:'Answer the voice',text:'Tell it who you have become.',effect:'will',requires:'will'},{label:'Seal the well',text:'Spend a supply and leave it silent.',effect:'seal'}]},
{id:'pilgrim',title:'A Pilgrim of Wax',icon:'♙',text:'A kneeling figure blocks the path. Every inch of it is candle wax, but a living eye turns within its melting face. “Carry my flame,” it begs.',choices:[{label:'Accept the flame',text:'Power has a price.',effect:'corrupt'},{label:'Extinguish it',text:'End this strange mercy.',effect:'fight'},{label:'Share your food',text:'Kindness in a dying world.',effect:'kind'}]},
{id:'door',title:'The Red Door',icon:'▣',text:'A crimson door stands alone in a ruined wall. Behind it, someone hums the lullaby sung at every funeral in Veyr.',choices:[{label:'Open it',text:'There are truths behind every door.',effect:'lore'},{label:'Listen closely',text:'Use cunning to learn safely.',effect:'cunning',requires:'cunning'},{label:'Mark it and leave',text:'Some doors are warnings.',effect:'leave'}]},
{id:'mirror',title:'A Mirror Full of Teeth',icon:'◇',text:'Your reflection is a heartbeat late. It smiles when you do not. Behind its teeth, a tiny version of the city burns.',choices:[{label:'Break the mirror',text:'Suffer no impostor.',effect:'hurt'},{label:'Trade reflections',text:'Become someone harder to kill.',effect:'trade'},{label:'Look away',text:'Keep what remains of yourself.',effect:'leave'}]}];
export const LORE=[
['The First Noon','Before the Meridian, noon lasted nine days. Crops turned white and men cast three shadows. The church called it a miracle until the shadows began speaking.'],
['The Bell Beneath','Veyr’s oldest bell was cast before the city. It rings only under water, tolling once for each citizen who will die before dawn.'],
['Saint Orra’s Heresy','Orra proved the gods could feel pain. The gods proved that saints could be erased. Both demonstrations were thorough.'],
['The Bone Titans','The continent rests upon creatures too large to have lived. Scholars disagree whether the bones are fossils or architecture.'],
['Letters from the Pass','General Vhal ordered his army to face south. “Whatever follows us from the north must believe we are unafraid.” They froze in formation.'],
['A Map of Other Veyrs','The astronomer Pell found twelve versions of the city in the night sky. In eleven, the walls had already fallen.']];
export const ORIGINS=[['Exiled Chirurgeon','Once a battlefield surgeon, now hunted for what you learned inside the dead.','+3 Will, Blood Mend'],['Grave Warden','You guarded the city’s dead until they began guarding you.','+3 Vigor, +1 Armor'],['Debt-Bound Scholar','The Collegium owns your name. The things in your books own the rest.','+3 Cunning, extra lore']];
export const PATHS=[['Vanguard','Meet horror edge-first.','+4 HP, Sever'],['Hexer','Name the darkness and make it kneel.','+4 Sanity, Cinder Hex'],['Vagrant','Survive through guile and quick hands.','+2 supplies, Riposte']];
export const COMPANIONS=[['Moth','A pale hound that growls at empty corners.','Finds supplies'],['Sister Cask','A disgraced nun with a loaded arquebus.','Combat support'],['Nix','A gutter raven that steals only important things.','Finds gold']];
