import{EVENTS,ITEMS,LORE,REGIONS,SKILLS}from'./content';import type{Enemy,GameState,Log}from'./types';
export const rand=(a:number,b:number)=>Math.floor(Math.random()*(b-a+1))+a;
export function fresh():GameState{return{version:1,screen:'title',name:'',origin:'',path:'',companion:'',difficulty:'Wayfarer',day:1,level:1,xp:0,xpNext:60,gold:65,supplies:6,hp:34,maxHp:34,sanity:24,maxSanity:24,vigor:5,will:5,cunning:5,armor:0,weapon:3,region:'catacombs',depth:0,maxDepth:8,enemy:null,event:null,inventory:['tonic','incense'],equipped:['rustblade'],skills:['sever'],cooldowns:{},questStep:0,lore:[],kills:0,bosses:0,corruption:0,guarding:false,log:[],settings:{sound:true,motion:true}}}
export function save(s:GameState){localStorage.setItem('dreadmarch-save',JSON.stringify(s))}
export function load():GameState|null{try{return JSON.parse(localStorage.getItem('dreadmarch-save')||'null')as GameState|null}catch{return null}}
export function setup(s:GameState){if(s.origin.includes('Chirurgeon')){s.will+=3;s.skills=['mend']}if(s.origin.includes('Warden')){s.vigor+=3;s.maxHp+=4;s.hp=s.maxHp;s.armor++}if(s.origin.includes('Scholar')){s.cunning+=3;s.lore.push('The First Noon')}if(s.path==='Vanguard'){s.maxHp+=4;s.hp=s.maxHp;s.skills.push('sever')}if(s.path==='Hexer'){s.maxSanity+=4;s.sanity=s.maxSanity;s.skills.push('cinder')}if(s.path==='Vagrant'){s.supplies+=2;s.skills.push('riposte')}s.skills=[...new Set(s.skills)];s.screen='city';save(s)}
export function region(s:GameState){return REGIONS.find(r=>r.id===s.region)!}
export function enemyFor(s:GameState,boss=false):Enemy{const tier=region(s).danger+(boss?2:0);const pools=[['Drowned Pilgrim','♙'],['Ash Hound','♞'],['Bone Prospector','☠'],['Frozen Deserter','♜'],['Meridian Echo','◐']];const [name,icon]=boss?[region(s).boss,'♛']:pools[Math.min(4,region(s).danger-1)];const hp=14+tier*7+(boss?18:rand(-2,4));return{id:`${Date.now()}`,name,icon,hp,maxHp:hp,damage:[2+tier,5+tier*2],sanity:Math.max(0,tier-1),armor:tier-1,trait:boss?'BOSS — acts twice below half health':['Bleeding touch','Hollow howl','Splintered armor','Deathly cold','Unreal geometry'][Math.min(4,tier-1)]}}
export function startFight(s:GameState,boss=false){s.enemy=enemyFor(s,boss);s.screen='combat';s.guarding=false;s.log=[{tone:'bad',text:`${s.enemy.name} blocks your path.`}];save(s)}
const push=(s:GameState,text:string,tone:Log['tone']='plain')=>{s.log.unshift({text,tone});s.log=s.log.slice(0,6)};
export function playerDamage(s:GameState,mult=1,ignore=false){const base=rand(s.weapon+Math.floor(s.vigor/3),s.weapon+4+Math.floor(s.vigor/2));return Math.max(1,Math.floor(base*mult)-(ignore?0:s.enemy?.armor||0))}
function tick(s:GameState){Object.keys(s.cooldowns).forEach(k=>s.cooldowns[k]=Math.max(0,s.cooldowns[k]-1))}
export function enemyTurn(s:GameState){if(!s.enemy||s.enemy.hp<=0)return;const e=s.enemy;let d=rand(...e.damage)-s.armor-(s.guarding?rand(2,5):0);d=Math.max(0,d);s.hp=Math.max(0,s.hp-d);let san=e.sanity&&Math.random()<.45?e.sanity:0;if(s.guarding)san=0;s.sanity=Math.max(0,s.sanity-san);push(s,`${e.name} deals ${d} damage${san?` and ${san} dread`:''}.`,'bad');s.guarding=false;tick(s);if(s.hp<=0){s.screen='ending';save(s)}}
export function win(s:GameState){const boss=s.enemy!.trait.startsWith('BOSS');const gain=12+region(s).danger*8+(boss?35:0);s.gold+=gain;s.xp+=gain;s.kills++;if(boss){s.bosses++;s.questStep=Math.max(s.questStep,s.bosses);s.depth=0;s.day++;push(s,`${s.enemy!.name} falls. The road ahead opens.`,'good')}if(Math.random()<.3)s.inventory.push(Math.random()<.5?'tonic':'incense');while(s.xp>=s.xpNext){s.xp-=s.xpNext;s.level++;s.xpNext=Math.floor(s.xpNext*1.35);s.maxHp+=4;s.hp=s.maxHp;s.maxSanity+=2;s.sanity=s.maxSanity;s.vigor++;push(s,`You reach level ${s.level}.`,'good')}s.enemy=null;s.screen=boss?'city':'dungeon';save(s)}
export function attack(s:GameState){if(!s.enemy)return;const d=playerDamage(s);s.enemy.hp=Math.max(0,s.enemy.hp-d);push(s,`You strike for ${d}.`,'good');if(s.enemy.hp<=0)win(s);else enemyTurn(s);save(s)}
export function defend(s:GameState){s.guarding=true;push(s,'You brace against the dark.');enemyTurn(s);save(s)}
export function flee(s:GameState){if(Math.random()<.55+s.cunning*.02){s.enemy=null;s.screen='dungeon';push(s,'You escape into the dark.','good')}else{push(s,'No escape.','bad');enemyTurn(s)}save(s)}
export function useSkill(s:GameState,id:string){const sk=SKILLS.find(x=>x.id===id);if(!sk||!s.enemy||s.cooldowns[id]>0)return;s.cooldowns[id]=sk.cooldown;if(sk.kind==='damage'){const d=playerDamage(s,id==='void'?2.15:1.55,id==='void');s.enemy.hp=Math.max(0,s.enemy.hp-d);push(s,`${sk.name} deals ${d}.`,'good')}else if(sk.kind==='heal'){s.sanity=Math.max(0,s.sanity-2);s.hp=Math.min(s.maxHp,s.hp+12);push(s,'Blood closes your wounds.','good')}else if(sk.kind==='sanity'){s.sanity=Math.min(s.maxSanity,s.sanity+8);push(s,'The noise within grows quiet.','good')}else{s.guarding=true;const d=playerDamage(s,1.1);s.enemy.hp=Math.max(0,s.enemy.hp-d);push(s,`Riposte deals ${d}.`,'good')}if(s.enemy.hp<=0)win(s);else enemyTurn(s);save(s)}
export function useItem(s:GameState,id:string){const i=s.inventory.indexOf(id);if(i<0)return;if(id==='tonic')s.hp=Math.min(s.maxHp,s.hp+14);if(id==='incense')s.sanity=s.maxSanity;s.inventory.splice(i,1);push(s,`Used ${ITEMS.find(x=>x.id===id)?.name}.`,'good');if(s.screen==='combat')enemyTurn(s);save(s)}
export function explore(s:GameState){if(s.supplies<=0){s.hp=Math.max(1,s.hp-5);s.sanity=Math.max(0,s.sanity-2)}else s.supplies--;s.depth++;if(s.depth>=s.maxDepth){startFight(s,true);return}const roll=Math.random();if(roll<.52)startFight(s);else if(roll<.84){s.event=structuredClone(EVENTS[rand(0,EVENTS.length-1)]);s.screen='event'}else{s.gold+=rand(8,22);s.inventory.push(Math.random()<.5?'tonic':'incense');push(s,'You discover an abandoned expedition cache.','good')}save(s)}
export function resolveEvent(s:GameState,effect:string,req?:'vigor'|'will'|'cunning'){let success=true;if(req)success=rand(1,12)+s[req]>=10;switch(effect){case'gold':s.gold+=22;s.sanity-=2;break;case'will':if(success)s.sanity=Math.min(s.maxSanity,s.sanity+6);else s.sanity-=4;break;case'seal':s.supplies--;s.sanity+=3;break;case'corrupt':s.weapon++;s.corruption++;s.sanity-=3;break;case'fight':startFight(s);return;case'kind':s.supplies--;s.hp=Math.min(s.maxHp,s.hp+8);break;case'lore':{const x=LORE.find(l=>!s.lore.includes(l[0]));if(x)s.lore.push(x[0]);s.sanity-=2;break}case'cunning':if(success)s.gold+=30;else s.hp-=5;break;case'hurt':s.hp-=4;s.sanity+=2;break;case'trade':s.maxHp+=3;s.maxSanity-=2;s.hp+=3;break}s.hp=Math.max(0,Math.min(s.maxHp,s.hp));s.sanity=Math.max(0,Math.min(s.maxSanity,s.sanity));s.supplies=Math.max(0,s.supplies);push(s,success?'Your choice leaves a mark.':'The dark rejects your certainty.',success?'good':'bad');s.event=null;s.screen='dungeon';save(s)}
export function rest(s:GameState){const cost=12+s.day*2;if(s.gold<cost)return;s.gold-=cost;s.day++;s.hp=s.maxHp;s.sanity=s.maxSanity;s.supplies+=2;save(s)}
export function buy(s:GameState,id:string){const i=ITEMS.find(x=>x.id===id);if(!i||s.gold<i.price)return;s.gold-=i.price;s.inventory.push(id);save(s)}
export function learn(s:GameState,id:string){const sk=SKILLS.find(x=>x.id===id);const cost=sk!.cost*80;if(s.gold<cost||s.skills.includes(id))return;s.gold-=cost;s.skills.push(id);save(s)}

export function equipItem(s:GameState,id:string){const item=ITEMS.find(x=>x.id===id);if(!item||!s.inventory.includes(id)||item.type==='consumable')return;if(item.type==='weapon')s.weapon=3+item.power;if(item.type==='armor')s.armor=item.power;s.equipped=s.equipped.filter(e=>ITEMS.find(x=>x.id===e)?.type!==item.type);s.equipped.push(id);push(s,`Equipped ${item.name}.`,'good');save(s)}
